apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hogfm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-hogfm
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
