apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogfm-api
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia
      containers:
        - name: api
          resources:
            limits:
              nvidia.com/gpu: "1"
